# Generated by Django 5.1.7 on 2025-03-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_cancelled',
        ),
    ]
