# Generated by Django 5.0.2 on 2025-06-05 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
